/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddFieldsSection: typeof import('./src/components/builder/sidebar/AddFieldsSection.vue')['default']
    DoctypeFieldsSection: typeof import('./src/components/builder/sidebar/DoctypeFieldsSection.vue')['default']
    FieldEditorSidebar: typeof import('./src/components/FieldEditorSidebar.vue')['default']
    FieldPropertiesForm: typeof import('./src/components/builder/FieldPropertiesForm.vue')['default']
    FieldRenderer: typeof import('./src/components/builder/FieldRenderer.vue')['default']
    FormBuilderContent: typeof import('./src/components/FormBuilderContent.vue')['default']
    FormBuilderHeader: typeof import('./src/components/FormBuilderHeader.vue')['default']
    FormBuilderSidebar: typeof import('./src/components/FormBuilderSidebar.vue')['default']
    FormHeader: typeof import('./src/components/submission/FormHeader.vue')['default']
    FormPreviewCard: typeof import('./src/components/dashboard/FormPreviewCard.vue')['default']
    FormRenderer: typeof import('./src/components/submission/FormRenderer.vue')['default']
    RenderField: typeof import('./src/components/RenderField.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section: typeof import('./src/components/fields/Section.vue')['default']
    SettingsSection: typeof import('./src/components/builder/sidebar/SettingsSection.vue')['default']
    SuccessSection: typeof import('./src/components/submission/SuccessSection.vue')['default']
  }
}
